dropout_rate: 0.3
label_smoothing_wt: 0.1
ment_loss: 'notall' # 'all'
normalize_loss: False
max_evals: 20
to_save_model: True
log_frequency: 240
patience: 5
eval_per_k_steps: null
num_training_steps: 1600
max_training_segments: 1